# Generated by Django 4.1.2 on 2022-11-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterSupplier",
            fields=[
                (
                    "kode_supplier",
                    models.CharField(
                        default="",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Kode Supplier",
                    ),
                ),
                (
                    "nama_supplier",
                    models.CharField(
                        default="", max_length=200, verbose_name="Nama Supplier"
                    ),
                ),
                (
                    "tlp1",
                    models.CharField(
                        default="", max_length=15, verbose_name="No. Telpon #1"
                    ),
                ),
                (
                    "tlp2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        null=True,
                        verbose_name="No. Telpon #2",
                    ),
                ),
                (
                    "alamat",
                    models.CharField(
                        default="", max_length=200, verbose_name="Alamat Supplier"
                    ),
                ),
                (
                    "hutang_awal",
                    models.PositiveIntegerField(default=0, verbose_name="Hutang Awal"),
                ),
                (
                    "hutang_tambahan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hutang Tambahan"
                    ),
                ),
                (
                    "hutang_akhir",
                    models.PositiveIntegerField(default=0, verbose_name="Hutang Akhir"),
                ),
                (
                    "catatan",
                    models.CharField(
                        default="-", max_length=200, verbose_name="Catatan"
                    ),
                ),
            ],
            options={
                "ordering": ["kode_supplier", "nama_supplier"],
                "unique_together": {("kode_supplier", "nama_supplier")},
            },
        ),
    ]
