# Generated by Django 4.1.3 on 2022-12-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos1_ecer',
            name='user_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pos1_grosir',
            name='user_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pos2_ecer',
            name='user_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pos2_grosir',
            name='user_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pos3_ecer',
            name='user_id',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
