# Generated by Django 4.1.3 on 2022-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos1_ecer',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='pos1_grosir',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='pos2_ecer',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='pos2_grosir',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='pos3_ecer',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='pos3_grosir',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='masterpelanggan',
            name='foto_ktp',
            field=models.ImageField(blank=True, null=True, upload_to='ktp', verbose_name='Foto KTP'),
        ),
        migrations.AlterField(
            model_name='masterpelanggan',
            name='tipe',
            field=models.CharField(choices=[('A', 'Pelanggan Harga#1'), ('B', 'Pelanggan Harga#2'), ('C', 'Pelanggan Harga#3'), ('E', 'Pelanggan Eceran')], max_length=1, verbose_name='Tipe Pelanggan'),
        ),
    ]
