# Generated by Django 4.1.2 on 2022-11-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kasir", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterPelanggan",
            fields=[
                (
                    "kode_pelanggan",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Kode Pelanggan",
                    ),
                ),
                (
                    "nama_pelanggan",
                    models.CharField(max_length=100, verbose_name="Nama Pelanggan"),
                ),
                (
                    "nomor_tlp",
                    models.CharField(max_length=15, verbose_name="Nomor Telepon"),
                ),
                (
                    "alamat_pelanggan",
                    models.CharField(max_length=100, verbose_name="Alamat KTP"),
                ),
                (
                    "foto_ktp",
                    models.ImageField(upload_to="ktp", verbose_name="Foto KTP"),
                ),
                (
                    "tipe",
                    models.CharField(
                        choices=[
                            ("A", "Pelanggan Harga#1"),
                            ("B", "Pelanggan Harga#2"),
                            ("C", "Pelanggan Harga#3"),
                        ],
                        max_length=1,
                        verbose_name="Tipe Pelanggan",
                    ),
                ),
            ],
            options={
                "ordering": ["kode_pelanggan", "nama_pelanggan"],
            },
        ),
    ]
