# Generated by Django 4.1.3 on 2022-11-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0002_masterpelanggan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBarang',
            fields=[
                ('id_barang', models.CharField(default='-', max_length=100, primary_key=True, serialize=False, verbose_name='ID Barang')),
                ('nama_barang', models.CharField(default='-', max_length=100, verbose_name='Nama Barang')),
                ('stok_awal', models.PositiveBigIntegerField(default=0, verbose_name='Stok Awal Barang')),
                ('stok_beli', models.PositiveBigIntegerField(default=0, verbose_name='Stok Pembelian')),
                ('stok_rusak', models.PositiveBigIntegerField(default=0, verbose_name='Stok Barang Rusak')),
                ('stok_akhir', models.PositiveBigIntegerField(default=0, verbose_name='Stok Barang Akhir')),
                ('harga_modal', models.PositiveBigIntegerField(default=0, verbose_name='Harga Modal')),
                ('harga_ecer', models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer')),
                ('harga_grosir1', models.PositiveBigIntegerField(default=0, verbose_name='Harga Grosir#1')),
                ('harga_grosir2', models.PositiveBigIntegerField(default=0, verbose_name='Harga Grosir#2')),
                ('harga_grosir3', models.PositiveBigIntegerField(default=0, verbose_name='Harga Grosir#3')),
                ('satuan_barang', models.CharField(choices=[('D', 'Kardus'), ('R', 'Renceng'), ('E', 'Ecer')], default='D', max_length=1, verbose_name='Satuan Barang')),
                ('keterangan_isi', models.CharField(max_length=100, verbose_name='Keterangan Isi')),
                ('foto', models.ImageField(upload_to='stok_barang', verbose_name='Foto Barang')),
            ],
            options={
                'ordering': ['id_barang', 'nama_barang'],
            },
        ),
    ]
