# Generated by Django 4.1.3 on 2022-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_masterbarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='hapus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterpelanggan',
            name='hapus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mastersupplier',
            name='hapus',
            field=models.BooleanField(default=True),
        ),
    ]
