# Generated by Django 4.1.3 on 2022-12-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_remove_pos1_ecer_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos1_ecer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos1_grosir',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos2_ecer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos2_grosir',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos3_ecer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos3_grosir',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
