# Generated by Django 4.1.3 on 2022-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0004_pos1_ecer_discount_pos1_grosir_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos1_ecer',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
        migrations.AddField(
            model_name='pos1_grosir',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
        migrations.AddField(
            model_name='pos2_ecer',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
        migrations.AddField(
            model_name='pos2_grosir',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
        migrations.AddField(
            model_name='pos3_ecer',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
        migrations.AddField(
            model_name='pos3_grosir',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
        migrations.AddField(
            model_name='posting',
            name='harga_barang',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Harga Ecer'),
        ),
    ]
