# Generated by Django 4.1.3 on 2022-12-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_pos1_ecer_harga_barang_pos1_grosir_harga_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos1_ecer',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos1_grosir',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos2_ecer',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos2_grosir',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos3_ecer',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos3_grosir',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='harga_modal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
