# Generated by Django 4.1.3 on 2022-11-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_masterparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angka', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angka', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
