# Generated by Django 4.1.3 on 2022-12-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0006_pos1_ecer_harga_modal_pos1_grosir_harga_modal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos1_ecer',
            name='nama_barang',
            field=models.CharField(default='-', max_length=100, verbose_name='Nama Barang'),
        ),
        migrations.AddField(
            model_name='pos1_grosir',
            name='nama_barang',
            field=models.CharField(default='-', max_length=100, verbose_name='Nama Barang'),
        ),
        migrations.AddField(
            model_name='pos2_ecer',
            name='nama_barang',
            field=models.CharField(default='-', max_length=100, verbose_name='Nama Barang'),
        ),
        migrations.AddField(
            model_name='pos2_grosir',
            name='nama_barang',
            field=models.CharField(default='-', max_length=100, verbose_name='Nama Barang'),
        ),
        migrations.AddField(
            model_name='pos3_grosir',
            name='nama_barang',
            field=models.CharField(default='-', max_length=100, verbose_name='Nama Barang'),
        ),
        migrations.AddField(
            model_name='posting',
            name='nama_barang',
            field=models.CharField(default='-', max_length=100, verbose_name='Nama Barang'),
        ),
    ]
