# Generated by Django 4.1.3 on 2022-11-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0006_data1_data2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data1',
        ),
        migrations.DeleteModel(
            name='data2',
        ),
    ]
