# Generated by Django 4.1.3 on 2022-12-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0007_pos1_ecer_nama_barang_pos1_grosir_nama_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='tanggal_trx',
            field=models.DateField(auto_now=True),
        ),
    ]
