# Generated by Django 4.1.3 on 2022-12-17 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kasir', '0008_posting_tanggal_trx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_nota', models.CharField(default='0', max_length=50)),
                ('tanggal_nota', models.DateField(auto_now=True)),
                ('tanggal_jtempo', models.DateField(auto_now=True)),
                ('jumlah_barang', models.PositiveIntegerField(default=0)),
                ('status_bayar', models.BooleanField(default=False)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.masterbarang')),
                ('kode_supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.mastersupplier')),
                ('nama_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal_nota', 'nomor_nota'],
                'unique_together': {('nomor_nota', 'kode_supplier', 'tanggal_nota')},
            },
        ),
        migrations.CreateModel(
            name='Pembelian_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_nota', models.CharField(default='0', max_length=50)),
                ('tanggal_nota', models.DateField(auto_now=True)),
                ('tanggal_jtempo', models.DateField(auto_now=True)),
                ('jumlah_barang', models.PositiveIntegerField(default=0)),
                ('posting', models.BooleanField(default=False)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.masterbarang')),
                ('kode_supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.mastersupplier')),
                ('nama_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal_nota', 'nomor_nota'],
                'unique_together': {('nomor_nota', 'kode_supplier', 'tanggal_nota')},
            },
        ),
    ]
