# Generated by Django 4.1.3 on 2022-11-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0008_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='pos1_ecer',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='pos1_grosir',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='pos2_ecer',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='pos2_grosir',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='pos3_ecer',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='pos3_grosir',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='posting',
            name='nomor_nota',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.CreateModel(
            name='Penjualan_Stok_Keluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_nota', models.CharField(default='0', max_length=12)),
                ('stok_jual', models.IntegerField(default=0)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.masterbarang')),
            ],
        ),
    ]
