# Generated by Django 4.1.3 on 2022-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0009_alter_pembayaran_nomor_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id_sistem', models.CharField(default='-', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
