# Generated by Django 4.1.3 on 2022-12-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0010_remove_pembelian_input_nama_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_barang', models.PositiveIntegerField(default=0)),
                ('harga_barang', models.PositiveBigIntegerField(default=0)),
                ('sub_total_harga', models.PositiveBigIntegerField(default=0)),
                ('disc_persen', models.PositiveIntegerField(default=0)),
                ('disc_rupiah', models.PositiveIntegerField(default=0)),
                ('pajak_persen', models.PositiveIntegerField(default=0)),
                ('pajak_rupiah', models.PositiveBigIntegerField(default=0)),
                ('total_harga', models.PositiveBigIntegerField(default=0)),
                ('posting', models.BooleanField(default=False)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.masterbarang')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian_NomorNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_nota', models.CharField(default='0', max_length=50)),
                ('tanggal_nota', models.DateField(auto_now=True)),
                ('tanggal_jtempo', models.DateField(auto_now=True)),
                ('selesai', models.BooleanField(default=False)),
                ('kode_supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.mastersupplier')),
            ],
            options={
                'ordering': ['tanggal_nota', 'nomor_nota'],
                'unique_together': {('nomor_nota', 'kode_supplier', 'tanggal_nota')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pembelian_posting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pembelian_posting',
            name='kode_barang',
        ),
        migrations.RemoveField(
            model_name='pembelian_posting',
            name='kode_supplier',
        ),
        migrations.RemoveField(
            model_name='pembelian_posting',
            name='nama_user',
        ),
        migrations.DeleteModel(
            name='Pembelian_Input',
        ),
        migrations.DeleteModel(
            name='Pembelian_Posting',
        ),
        migrations.AddField(
            model_name='pembelian_detail',
            name='nomor_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.pembelian_nomornota'),
        ),
    ]
