# Generated by Django 4.1.3 on 2022-12-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0010_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='id_sistem',
            field=models.CharField(default='-', max_length=6, primary_key=True, serialize=False),
        ),
    ]
