# Generated by Django 4.1.3 on 2022-12-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0012_parameter_counter1_ecer_parameter_counter1_grosir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos1_ecer',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos1_grosir',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos2_ecer',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos2_grosir',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos3_ecer',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pos3_grosir',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
