# Generated by Django 4.1.3 on 2022-12-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0012_alter_pembelian_nomornota_tanggal_jtempo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelian_detail',
            old_name='posting',
            new_name='proses',
        ),
        migrations.RenameField(
            model_name='pembelian_nomornota',
            old_name='selesai',
            new_name='proses',
        ),
    ]
