# Generated by Django 4.1.3 on 2022-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0013_rename_posting_pembelian_detail_proses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterparameter',
            name='stok_minus',
            field=models.BooleanField(default=False),
        ),
    ]
