# Generated by Django 4.1.3 on 2022-12-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0014_alter_pos1_ecer_user_id_alter_pos1_grosir_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos1_ecer',
            name='id_barang',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos1_ecer',
            name='kode_pelanggan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos1_ecer',
            name='kode_sistem',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos1_grosir',
            name='id_barang',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos1_grosir',
            name='kode_pelanggan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos1_grosir',
            name='kode_sistem',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos2_ecer',
            name='id_barang',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos2_ecer',
            name='kode_pelanggan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos2_ecer',
            name='kode_sistem',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos2_grosir',
            name='id_barang',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos2_grosir',
            name='kode_pelanggan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos2_grosir',
            name='kode_sistem',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos3_ecer',
            name='id_barang',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos3_ecer',
            name='kode_pelanggan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos3_ecer',
            name='kode_sistem',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos3_grosir',
            name='id_barang',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos3_grosir',
            name='kode_pelanggan',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='pos3_grosir',
            name='kode_sistem',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
