# Generated by Django 4.1.3 on 2022-12-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kasir', '0014_masterparameter_stok_minus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPenyesuaianStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now=True)),
                ('penambahan', models.IntegerField(default=0)),
                ('pengurangan', models.IntegerField(default=0)),
                ('alasan', models.CharField(max_length=200)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kasir.masterbarang')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
